name: ci-default-skip

on:
  push:
    branches:
    pull_request:
    paths-ignore:
    - '.github/workflows/ci-default.yml'
    - 'templates/default/**'

jobs:
  build:
    name: default-build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        node: [12, 14, 16]
        dir: ['templates/default']
    steps:
      - run: 'echo "No build required" '
