name: ci-default

on:
  push:
    branches:
    pull_request:
    paths:
    - '.github/workflows/ci-default.yml'
    - 'templates/default/**'

jobs:
  build:
    name: default-build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        node: [12, 14, 16]
        dir: ['templates/default']
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: templates/default/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
