name: ci-typescript-skip

on:
  push:
    branches:
    pull_request:
    paths-ignore:
    - '.github/workflows/ci-typescript.yml'
    - 'templates/typescript/**'

jobs:
  build:
    name: typescript-build
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
