name: ci-typescript

on:
  push:
    branches:
      - main
    paths:
    - '.github/workflows/ci-typescript.yml'
    - 'templates/typescript/**'
  pull_request:
    branches:
      - main
    paths:
    - '.github/workflows/ci-typescript.yml'
    - 'templates/typescript/**'

jobs:
  build:
    name: typescript-build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        node: [16, 18, 20]
        dir: ['templates/typescript']
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: templates/typescript/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
