name: ci-default

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    name: default-build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        node: [16, 18, 20]
        dir: ['templates/default', 'templates/typescript']
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: templates/default/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

  publish-npm:
    runs-on: ubuntu-latest
    if: success() &&
      github.event_name == 'release' &&
      github.event.release.target_commitish == 'main'
    environment: npm
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
